version: 0.2

env:
  variables:
    AWS_REGION: eu-north-1
    ACCOUNT_ID: 287216490901
    CLUSTER_NAME: hello-world-eks2
    DEPLOYMENT_NAME: hello-deployment
    CONTAINER_NAME: hello-container
    IMAGE_REPO_NAME: hello-world-ecr2
    IMAGE_TAG: latest

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "Installing kubectl"
      - KUBECTL_VERSION=$(curl -sL https://dl.k8s.io/release/stable.txt)
      - echo "Latest kubectl version is $KUBECTL_VERSION"
      - curl -LO "https://dl.k8s.io/release/$KUBECTL_VERSION/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/kubectl
      - kubectl version --client

  pre_build:
    commands:
      - echo "Updating kubeconfig"
      - aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
      - export KUBECONFIG=/root/.kube/config
      - echo "Verifying access to EKS"
      - kubectl get nodes || (echo "kubectl failed" && exit 1)
      - echo "Logging into ECR"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo "Building Docker image"
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Docker image to ECR"
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo "Updating deployment in EKS"
      - kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER_NAME=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo "Forcing rollout with annotation"
      - kubectl patch deployment $DEPLOYMENT_NAME -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"build-timestamp\":\"$(date +%s)\"}}}}}"
      - echo "Waiting for rollout to complete"
      - kubectl rollout status deployment/$DEPLOYMENT_NAME

artifacts:
  files:
    - webapp.war
