version: 0.2

env:
  variables:
    AWS_REGION: eu-north-1
    ACCOUNT_ID: 287216490901
    IMAGE_REPO_NAME: hello-world-ecr2
    IMAGE_TAG: latest

phases:
  install:
    runtime-versions:
      java: corretto21
      docker: 20

  pre_build:
    commands:
      - echo "Logging into ECR"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo "Building WAR file"
      - mvn clean package -DskipTests
      - echo "Copying WAR to Docker context"
      - cp webapp/target/webapp.war .
      - echo "Building Docker image"
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Docker image to ECR"
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

artifacts:
  files:
    - webapp/target/webapp.war
