version: 0.2

env:
  variables:
    AWS_REGION: eu-north-1
    ACCOUNT_ID: 287216490901
    IMAGE_REPO_NAME: hello-world-ecr2
    IMAGE_TAG: latest
    JAVA_VERSION: corretto11  # compatible with older Maven project

phases:
  install:
    runtime-versions:
      java: $JAVA_VERSION
      docker: 20
    commands:
      - echo "Installing Maven (if not preinstalled)"
      - mvn -version
      - echo "Logging into ECR"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  pre_build:
    commands:
      - echo "Ensuring ECR repository exists"
      - aws ecr describe-repositories --repository-names $IMAGE_REPO_NAME || aws ecr create-repository --repository-name $IMAGE_REPO_NAME
      - echo "Cleaning previous builds"
      - mvn clean

  build:
    commands:
      - echo "Building WAR file"
      - mvn clean package -DskipTests
      - echo "Checking if WAR exists"
      - if [ ! -f webapp/target/webapp.war ]; then echo "WAR file not found! Build failed."; exit 1; fi
      - echo "Copying WAR to Docker build context"
      - cp webapp/target/webapp.war .
      - echo "Building Docker image"
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Docker image to ECR"
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo "Docker image successfully pushed:" $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

artifacts:
  files:
    - webapp/target/webapp.war
