version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    ACCOUNT_ID: 287216490901
    CLUSTER_NAME: hello-world-eks
    DEPLOYMENT_NAME: hello-deployment
    CONTAINER_NAME: hello-container
    ECR_REPO_NAME: hello-world-ecr
    IMAGE_TAG: latest

phases:
  install:
    runtime-versions:
      java: corretto17
      docker: 20
    commands:
      - echo "Installing kubectl..."
      - curl -sS -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.27.3/2023-07-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
      - echo "Updating kubeconfig for EKS cluster..."
      - aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo "Building WAR with Maven..."
      - mvn clean package -DskipTests
      - echo "Building Docker image..."
      - docker build -t $ECR_REPO_NAME:$IMAGE_TAG .
      - docker tag $ECR_REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG
      - echo "Updating EKS deployment..."
      - kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER_NAME=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG
      - echo "✅ Deployment updated successfully!"

artifacts:
  files:
    - target/*.war
